### ISSUE TITLE
How to post cropped image via php

### ISSUE THREAD

**Issue by yash82** [MattKetmo/darkroomjs#121]
Hi 

I am using darkroom JS for cropping image but not able to process cropped image via PHP form.

Can you please provide a sample code to process image with PHP.

Regards

**Comment by moezzie** [comment]
You should be able to get the image data as an data url directly from the canvas.  
The resulting data url you can post to your server via an ajax request for example.

```
var canvas        = document.getElementById("mycanvas");  
var imgDataUrl    = canvas.toDataURL("image/png");
```

**Comment by yash82** [comment]
Hi Moezzie

I have make it working now, thanks for your suggestion.

Can you please let me know why the footer is getting distance after including darkroom.js file. 

After including the darkroom.js file , footer is getting some extra white space.

Regrads
