### ISSUE TITLE
Image ViewPort Size

### ISSUE THREAD

**Issue by tenbits** [MattKetmo/darkroomjs#13]
Hi Matthieu, 
i would like to set the maxWidth for the viewport(container div) only, not the canvas. Let me explain with example: There is an image which I want to crop: `1000x1000px`; The browsers width is e.g. `500px`; So now I want canvas itself to remain `1000x1000px`, but the canvas element set for `500x500px`.
As for now, when I set `maxWidth:500`, then it shows me as desired: `500x500px`, but it also scales the canvas itself to `500x500px`, it means the original image is also scaled. So when I crop some region of e.g. `50%`, I have then the image `250x250px`, but it should be `500x500px`, as original image is `1000x1000px`. 

I can set `max-width` and `max-height` of the `darkroom-image-container` for `500x500px`,  and it works great : canvas remains `1000x1000px`; but then there are problems with cropping plugin, as it paints cropping area not correctly. 

I will dig deeper into this, but also created an issue in case you have some solution for this, or some tips?

_Hopefully my explanation was not so bad)_

Cheers, Alex

**Comment by MattKetmo** [comment]
This should be fixed with v2.0.0
