### ISSUE TITLE
width/height vs naturalWidth/naturalHeight after saving

### ISSUE THREAD

**Issue by cestcri** [MattKetmo/darkroomjs#18]
I would like to save images (big ones, scaled down with CSS to be darkroomed) while maintaining original dimensions. Looks like the img > canvas conversion reduces the dimension of the image to those on the screen, and not the naturalWidth/naturalHeight of the initial image.

Any idea how to remedy this?

https://github.com/MattKetmo/darkroomjs/pull/14 seems to address the same issue.

**Comment by MattKetmo** [comment]
Fixed with v2.0.0
