### ISSUE TITLE
when darkroomjs is inside a form which has html5 validation, clicking button triggers validation

### ISSUE THREAD

**Issue by christhomas** [MattKetmo/darkroomjs#24]
When you want to allow the user to select an image and use darkroomjs on it, it'll create a button bar with a lot of buttons inside.

if that form has required validation elements, clicking any button in the button bar will trigger validation events, those events may ruin the user experience because it'll navigate to that element and show the failed validation message.

however the button will still work correctly

the reason for this is by default "button" html elements are of type "submit" and this means any clicking will trigger a validation pre submit event, which then triggers any validation warnings, blocking the submit event from happening.

attempting to catch the "invalid" event won't work since even if you do catch it, you can't accurately know it was the darkroomjs button which caused it since the invalid event can't be delegated, you need to trap it directly on the node which caused the validation error, meaning you can't know which button caused the invalid event to trigger

the only solution I've been able to find is to change the button type from "submit" to "button"

in the javascript of darkroom.js, line 124, where the button is created, you can add the following line, it'll fix the errro

    button.type = "button";

I've already tried this and it was working just fine and everything is happening exactly as I expect it to.

**Comment by digz6666** [comment]
Thank you for sharing your solution!

**Comment by MattKetmo** [comment]
Thanks I've fixed it in 60f4a98.

**Comment by digz6666** [comment]
Oh thanks!
