### ISSUE TITLE
crop area and drag handles not aligned

### ISSUE THREAD

**Issue by christhomas** [MattKetmo/darkroomjs#25]
I've noticed sometimes when I draw a crop area, it appears to the left of the area where I'm creating it and also the handles dont work, but when you move the mouse over to the right roughly the same distance that the crop area is displaced, you'll find it shows the crop handle.

very strange, but I've found it consistently with one image I've got, but I'm trying to narrow down why it would happen

**Comment by MattKetmo** [comment]
Hello. I'm closing this issue since it's quite old and the code changed since then (sorry for the non-answer).  

Feel free to reopen is necessary.
