### ISSUE TITLE
Can you please post a release build

### ISSUE THREAD

**Issue by rogier21** [MattKetmo/darkroomjs#26]
I'm not a JS developer and I have been fiddling with JS, Node and grunt but I cant get it to build. Now I am stuck on an error with webfont again.

Could you please add a release so people don't need to build themselves?

**Comment by ddcovery** [comment]
+1 for this.

**Comment by lucascourot** [comment]
:+1:

**Comment by natecox** [comment]
I have a pull request open that exposes the `/build` directory by default, which I believe is the expected and normal behavior for a bower package.

https://github.com/MattKetmo/darkroomjs/pull/38

**Comment by natecox** [comment]
Same request referenced here: https://github.com/MattKetmo/darkroomjs/issues/22

**Comment by MattKetmo** [comment]
Fixed via #38 (and sorry for the delay)
