### ISSUE TITLE
very needed features for web publishing

### ISSUE THREAD

**Issue by ericq** [MattKetmo/darkroomjs#32]
Good tool and framework. can you have the following features that are very needed for web page publishing. 
1) drag and drop a new image file
2) scaledown high resolution image automatically to save network bandwidth
3) resize the image to different height or width. also support resize one input to multiple predefined size (e.g. thumbnail view)
4) add watermark with provided text

**Comment by ericq** [comment]
There is a bounty on this issue. https://www.bountysource.com/issues/7445549-very-needed-features-for-web-publishing

**Comment by sible777** [comment]
Do you have any specifications as to what resolution you want to consider high resolution?

**Comment by xptest18** [comment]
I think anything that is bigger than a normal desktop browser web view can be seen as high resolution in this web publishing context. (i.e. bigger than 1024 * 768). Here is an example: 
Here is an example. https://github.com/kangax/fabric.js/blob/master/test/fixtures/very_large_image.jpg. In the web authoring phase, the inexperienced end user tend to upload whatever image they have in hand and forgot to scale them down to optimize them for speedy network transfer. In my opinion, a file should be less than 100KBytes for large picture (make Jpeg (high quality) as a good format) for general use cases and png for much smaller images and the use cases where transparent background is needed.

**Comment by sible777** [comment]
I just implemented the ability to drag and drop an image from the users computer directly to the canvas. It is still hacky though and I will need to test thoroughly, after that I can begin to work on the image scale down.

**Comment by ericq** [comment]
my comment to scale-down a high quality jpg file : the scaled down version should be  1080*720  (max width or height) and the dpi is 72 dpi. This is a good example of such an example http://fengyuanchen.github.io/cropper/img/picture-1.jpg
This image is 1280*720 in 72dpi. It's about 160KB. It's good for transfer and web-viewing. If we can scale down the 5M (zebra jpg) to this size. it will be very good.

**Comment by sible777** [comment]
Okay, good to know, I will keep those specifications in mind. The main time consumer will be studying the existing code base and integrating my code properly. I will continue working on the desired features tomorrow evening or perhaps the day after tomorrow as uni is starting back up and I must move back to school tomorrow.

Cheers

**Comment by Ahimta** [comment]
@ericq I would like to start working on this if the bounty on Bountysource still up and @sible777 doesn't mind.

**Comment by sible777** [comment]
I don't mind if you start working on it. I have been extremely busy with
university projects and haven't had much time to finish up my code.

On Sat, Jan 24, 2015 at 12:56 PM, Abdullah Alansari <
notifications@github.com> wrote:

> @ericq <https://github.com/ericq> I would like to start working on this
> if the bounty on Bountysource still up and @sible777
> <https://github.com/sible777> doesn't mind.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MattKetmo/darkroomjs/issues/32#issuecomment-71329487>.
>



-- 
ಠ_ಠ ಠ_ಠ ಠ_ಠ ಠ_ಠ ಠ_ಠ ಠ_ಠ ಠ_ಠ ಠ_ಠ ಠ_ಠ

**Comment by ericq** [comment]
@Ahimta, welcome. It's still up. it's valid for about 3 months till beginning of March.

**Comment by Ahimta** [comment]
Hi @grimor, I've been working on this issue for sometime.
You can find my code on my fork [here](https://github.com/Ahimta/darkroomjs).

Every feature is in its own branch.
Current status:

1. Resize plugin: implemented using fabricjs (there's room for improvement).
2. Watermark plugin: implemented using <input type='color'/> which is not supported in all browsers, in addition it needs some styling.
3. Drag and drop: implemented for dragging images from the desktop and works in Chorme, Firefox and Opera and should work on IE (unfortunately, I am using Ubuntu and don't want to reboot to Windows in the foreseeable future), will add support for dragging images from the DOM (probably today).
4. Thumbnail: haven't started working on it yet.
5. Scale down high resolution images automatically is mostly here using by passing the options: min{Height,Width}, max{Height,Width}

@grimor if you have any other questions, or just want to chat you can email me or Skype or whatever.
And please don't smoke it's bad for your health.

**Comment by Ahimta** [comment]
Just finished working on the issue. you can find my PR here #39.

**Comment by ericq** [comment]
@Ahimta , thanks for the update. Since I'm pretty new to how the GitHub works, could you please tell me how to do some testing with your work? or, if you can put together a demo link, it will be better. So I can give you the feedback and can help to close the issue.

**Comment by Ahimta** [comment]
Sure. You can find the demo [here](http://ahimta.github.io/darkroomjs/).

**Comment by ericq** [comment]
@Ahimta,
Some general comments first:
- the buttons you added (e.g. the watermark) only shows up in the chrome. It does work in Safari, while the original project demo works in both browser. 

- the undo / redo buttons are not integrated. for example, I dragged in a new picture and start the editing. If I click the undo button, the editor shows the image (old one) before the dragging.  This is common to other work as well (e.g. the watermark).

Specific comments per the requirements:
1) drag and drop a new image file
[comments] It works for both png and jpg. (good) and it works for pretty large pic 4.5M and it optimized the size automatically. (good)
1.a But when I used this 5.2M (3778*5129) photo, it did not work. I had this for the test 
https://dl.dropboxusercontent.com/u/51757570/zebra.jpg [need improvement] 
1.b If I use this picture, you can notice the ratio has bee changed. can you help to see why? https://dl.dropboxusercontent.com/u/51757570/wm1.jpg

2) scaledown high resolution image automatically to save network bandwidth
[comments] tested. (good)

3) resize the image to different height or width. also support resize one input to multiple predefined size (e.g. thumbnail view)
[comments] I clicked on the button with 4-small-windows. I think this is for the thumbnail view. but it does not respond to any size I put in the form. 
I think the thumbnailing feature we're building here is more like scale up/down the image while preserving the ratio first and then cropping it to meet the specified size. 

4) add watermark with provided text
[comments]  The text are in vector fonts and I can resize it freely (good) 
how difficult to specify the font type (?)

p.s. sorry for the late response. I was sick last week.

**Comment by Ahimta** [comment]
@ericq thanks for your detailed feedback, seriously.
Hopefully I will finish working on these issues by the end of the week.

**Comment by Ahimta** [comment]
@ericq

Undo/redo functionality now works better with other plugins.
In addition many memory leaks and using wrong reference are fixed.

1. Drag and drop: the issue was that there is a limit for the size of the dropped file size as a sanity check (configurable via the option "maxFileSize: {size in bytes}").
The default maximum file size was 5MB (10MB now). In addition this plugin requires that IndexedDB is supported, for example Epiphany and Midori don't.

2. Scale-down high resolution image automatically to save network bandwidth:
In fact Darkroom scales-down large images and scales-up small images and this is configurable
via the options: {minWidth,minHeight,maxWidth,maxHeight}.

3. Thumbnail plugin: you can use it by specifying either scale or height and width
and then click on the add icon to add it to the thumbnails.

4. Watermark plugin: you can now make it bold or italic and specify the font type by writing it.

**Comment by ericq** [comment]
@Ahimta I did see the improvements. Great progress!
Here are some findings and could you give some comments back:
1) the drag and drop works in Chrome, not Safari.
2) Thumbnail not working. I tried the scale and the width. It does not work.

**Comment by Ahimta** [comment]
@ericq

1. I made some changes on drag and drop plugin. It should work on almost any reasonably new browser.
It no longer requires IndexedDB and doesn't use a polyfill (darkroomjs is polyfill-free again).
It works on Chrome, Firefox, IE and Opera, but not on Epiphany and Midori, which are Webkit browsers (could be related to Safari).
Unfortunately, it doesn't work on Safari 5.1.7 (I don't have a MAC), and so didn't Mediafire drag and drop functionality.
Please try it on Safari and tell me what version if it didn't work.

2. I tried thumbnail plugin on Chrome, Firefox, Opera, IE, Safari 5.1.7, Epiphany and Midori, and it worked for me.
I think it could be a UX issue that makes not so obvious how to use the plugin.
You can find a video illustrating how to use the plugin [here](http://youtu.be/DMFym4Cr41E).

**Comment by ericq** [comment]
1. the drag & drop now works in both Safari and Chrome now. This is good. Btw, I'm using Safari 8.0

2. The thumbnail now also works. I think there was some inconsistence in the UX design, thus the confusion. After the Thumbnail view is selected, You have "+", "check", "cross" 3 buttons added. I will suggest to use "check" to apply changes (just to mimic the crop action). If you want to keep "+", it should automatically increase the size by x (default = 5%) pixels, then you should also have "-" button to shrink it.  Here is the suggest list of buttons for the toolbar (from left to right):
 + button : increase the size by 5%
 -  button: decrease the size by 5%
scale input / width/ height  /dimension
check box : keep ratio or not. In this way, we allow user to provide only one value for width or height.
 check button: apply the changes specified in the custom field. after the click, the entire "thumbnail" toolbar should disappear
 cross button: ignore the values set in the custom field and the entire "thumbnail" toolbar should disappear

3. Some bugs with the thumbnail: 
- after the "check" is selected, the red "cross" is still there. It should not be. 
- the redo/undo is NOT integrated

4. The thumbnail function has been implemented so far was a "resize" function to resize the image/canvas.When I thought about "thumbnail" view, I was also thinking about a zoom in/out function in addition to resize. I think it might be easier that we separate "resize" from "zoom in/out". zoom in/out does not change the size of the canvas. feel free to let me know your thoughts. :)

**Comment by Ahimta** [comment]
I made some changes to the thumbnail plugin you can try it [here](http://ahimta.github.io/darkroomjs).
As for the zoom in/out, I think that zoom in corresponds to the crop operation and zoom out to scaling-down the image.

Now that I realized my true UX skills, I feel like [Original Android Logo Was A Truly Frightening Robot](http://www.huffingtonpost.com/2013/01/04/original-android-logo-robot_n_2410568.html)

**Comment by ericq** [comment]
Just love the changes. :)

Do you think you can do the following so we can close this issue. 
1) change the "thumbnail" icon to something more intuitive. It should be something like "resize"
2) in the "resize", every time user clicks the + or - to change the size, can you show the height/width in the height/width field so users know the current size.
3) have a look on http://fengyuanchen.github.io/cropper/ and you will see zoom in/out. It's the magnifier with + and - sign.  It will make this thing complete
4) also please let me know how to provide custom code when the "save" button is clicked. I want to trigger an upload to server.
4) is it possible to merge it to the main code base? otherwise, do we need to download form the forked one?

Thanks. Look forward to close the issue soon.

**Comment by Ahimta** [comment]
- [x] change the thumbnail to something more intuitive.
- [x] update width and height fields when the user clicks '+' or '-' button.
- [x] I pulled the latest code from upstream (original repo) and the fork can be merged back to the main codebase.
- [ ] I will start working on the zoom plugin later, probably, after I finish [Algorithms, Part II](https://www.coursera.org/course/algs4partII) second assignment, which is implementing [Seam Carving](https://youtu.be/6NcIJXTlugc) ([wiki](https://youtu.be/6NcIJXTlugc)), efficiently. Maybe I will implement this feature in the future in fabricjs and darkroomjs, if there's enough demand for it.
- [x] you can pass your custom code when save is clicked
```javascript
var darkroom = new Darkroom({

  plugins: {

    save: {

      callback: function() {

        // the function is bound to the plugin object
        var canvas = this.darkroom.canvas,
            image  = this.darkroom.image;
      }
    }
  }
});
```

As a side note, if you want to upload an image to the server using multipart forms, which you will probably do, then in some cases it can be easier to make the multipart request contain only files and another regular PUT or POST request that contains the rest data.

**Comment by Ahimta** [comment]
@ericq I just finished working on the zoom plugin check it out [here](http://ahimta.github.io/darkroomjs/)

**Comment by ericq** [comment]
The zoom is very nice, especially with the bonus feature of specifying the center of the zooming area. 

And I tested it using Safari, Chrome and IE (v11) browsers, I found some minor issues
1) The color pick widget only works in Chrome, not Safari or IE. On the latter two browsers, it does not show the color but the code only like "#000000". and if you click on it, it does not show the color pick  widget. 
2) IE only, in the resize mode and the watermark mode, the width of the text field is pretty wide and pushes everything to the very right and even a horizontal scroll bar was triggered.

Could you please let me know how easy to fix those?

**Comment by Ahimta** [comment]
I made some changes, you can try it [here](http://ahimta.github.io/darkroomjs)

**Comment by ericq** [comment]
Both are fixed now. The color picker now is cross 3-browser now. :)
1) I have a question about the font type. Do you expect people to type in? or it's a drop down? 
2) Also, (I'm sorry for this), can I suggest the last thing in this thread: it's about "the crop" - can you add width / height  into the toolbar (after the X sign button?) so it will show the size of the cropping window or user can specify the cropping window size. I think with this feature, user can create a thumbnail image from the original copy. Otherwise, it's very difficult for them to create a, say 100*80, thumbnail image. With this feature, they can do it easily.

**Comment by ericq** [comment]
Ahimta, I closed the issue here. so please go to the sourcebounty to claim the bounty. It's only a small token of appreciation. When you have time please help to add the features I asked above.

**Comment by Ahimta** [comment]
@ericq You can now select the font from a select menu in the watermark plugin and specify the width and height in the crop plugin
