### ISSUE TITLE
Cropping causes black corners

### ISSUE THREAD

**Issue by RossLote** [MattKetmo/darkroomjs#44]
![thwaites-triple_c2-thumb_odbavnv](https://cloud.githubusercontent.com/assets/1877650/6967566/0943ae9c-d958-11e4-9ca4-a7a26ee05b1d.jpg)

**Comment by bazjapan** [comment]
was just about to take a look at this myself.  I suspect the cropCurrentZone method needs a tweak - maybe hide the handles before calling canvas.toDataURL.
Did you have any luck?

**Comment by ericfreese** [comment]
It looks to me like this is caused by [this line](https://github.com/RossLote/darkroomjs/blob/master/lib/js/plugins/darkroom.crop.js#L416) not causing the canvas to re-render. The line ought to be removed and replaced with `this.cropZone.remove();` no?

**Comment by sathio** [comment]
@ericfreese yes, this fixes it for me

**Comment by RossLote** [comment]
@ericfreese  Yeah, that was my fix too.

**Comment by MattKetmo** [comment]
This should be fixed with version 2.0.0
