### ISSUE TITLE
Grunt builds teeny-tiny icons on Windows

### ISSUE THREAD

**Issue by hujhax** [MattKetmo/darkroomjs#46]
If I build this project with grunt on Windows (setting engine: 'node' in the webfont options), then I wind up with an interface that has itty-bitty icons:
![itty-bitty images](http://ft.trillian.im/0d2d46258c572aa7f4a70e4192df6de4690788fa/6xTBnmTm5MA3zRO8HlPCx73LVqKYR.jpg)

They're nearly invisible!

**Comment by MattKetmo** [comment]
Hello. You can try the `v2` branch which doesn't use a custom font face anymore.

**Comment by MattKetmo** [comment]
Fixed with v2.0.0
