### ISSUE TITLE
Hiding a toolbar option

### ISSUE THREAD

**Issue by theminniti** [MattKetmo/darkroomjs#47]
Can I hide the save button?  I don't have a use for it, and would like to not show it as it could be confusing, if it's there but does nothing.

**Comment by MattKetmo** [comment]
Yep, totally. See the usage example in the readme:

```js
new Darkroom('#target', {
  // ...
  plugins: {
    save: false // disable plugin
  },
});
```

**Comment by theminniti** [comment]
Thanks Matt.  Great plugin.
