### ISSUE TITLE
Bower Version doesn't match specific version numbers, only by *

### ISSUE THREAD

**Issue by Dezzymei** [MattKetmo/darkroomjs#48]
I am setting up bower to pull in the dependency for darkroom, but there is no specific version number so it has to match by the *.

Doing a "bower install darkroomjs -S" appends to my bower.json:
"darkroomjs": "*"

However it doesn't have a version number. I believe this is because the versioning on the branches doesn't match the expected bower format: (http://stackoverflow.com/questions/26571739/bower-install-no-versions-available). 

I don't know how to fix this but could have a go as if master updates it will update in our codebase whenever we do an update.

Thanks

**Comment by apfelbox** [comment]
@Dezzymei it seems that there are proper releases since about 2 weeks: https://github.com/MattKetmo/darkroomjs/releases
