### ISSUE TITLE
add callback to button

### ISSUE THREAD

**Issue by sathio** [MattKetmo/darkroomjs#50]
Hi, I was wondering if it's possible to add a callback to the crop/accept button

**Comment by z3dev** [comment]
init: function() {
        var cropPlugin = this.getPlugin('crop');
        var xoffset = (canvasSize - cropSize) / 2;
        cropPlugin.okButton.addEventListener('click',hello,false);
        cropPlugin.selectZone(xoffset, xoffset, cropSize, cropSize);
      }

**Comment by digz6666** [comment]
Thanks you for your hint.

**Comment by digz6666** [comment]
@z3dev Thanks you for your hint.
