### ISSUE TITLE
How to reload the image?

### ISSUE THREAD

**Issue by z3dev** [MattKetmo/darkroomjs#53]
Hi Matt and Company,

I've been playing with Darkroom and like the functionality and design. However, one of the requirements for my website is to allow a user to load a image locally into the browswer, and use Darkroom to change the image. And of course, send the results to the webserver.

It's not a slam dunk... Darkroom doesn't provide this functionality, so I had to develop some pretty ugly routines to reset the contents of the Darkroom.canvas and Darkroom.image.

I think that with a few changes, Darkroom could support this very easily.

**Comment by z3dev** [comment]
<script>
    var canvasSize = document.getElementById("img-canvas").clientHeight;
    var cropSize = canvasSize * 0.80;
    var dkrm = null;
    loadDarkroom();

    function loadDarkroom() {
console.log("reloading...");
      dkrm = new Darkroom('#design-image', {
        // canvas options
        minWidth: canvasSize,
        minHeight: canvasSize,
        //maxWidth: 500,
        //maxHeight: 500,
  
         plugins: {
           save: false,
           history: false,
           crop: {
             quickCropKey: 67, //key "c"
             minHeight: cropSize,
             minWidth: cropSize,
             ratio: 1
           }
         },
         init: function() {
           var cropPlugin = this.getPlugin('crop');
           var xoffset = (canvasSize - cropSize) / 2;
           cropPlugin.selectZone(xoffset, xoffset, cropSize, cropSize);
         }
       });
    }
    function scaleImage(image) {
      var width = image.getWidth();
      var height = image.getHeight();
      var scaleMin = 1;
      var scaleMax = 1;
      var scaleX = 1;
      var scaleY = 1;

      if (null !== dkrm.options.maxWidth && dkrm.options.maxWidth < width) {
        scaleX =  dkrm.options.maxWidth / width;
      }
      if (null !== dkrm.options.maxHeight && dkrm.options.maxHeight < height) {
        scaleY =  dkrm.options.maxHeight / height;
      }
      scaleMin = Math.min(scaleX, scaleY);
//console.log("scaleX: "+scaleX);
//console.log("scaleY: "+scaleY);
//console.log("scaleMin: "+scaleMin);

      scaleX = 1;
      scaleY = 1;
      if (null !== dkrm.options.minWidth && dkrm.options.minWidth > width) {
        scaleX =  dkrm.options.minWidth / width;
      }
      if (null !== dkrm.options.minHeight && dkrm.options.minHeight > height) {
        scaleY =  dkrm.options.minHeight / height;
      }
      scaleMax = Math.max(scaleX, scaleY);
//console.log("scaleX: "+scaleX);
//console.log("scaleY: "+scaleY);
//console.log("scaleMax: "+scaleMax);

      var scale = scaleMax * scaleMin; // one should be equals to 1

      image.setScaleX(scale);
      image.setScaleY(scale);

      return image;
    }
    function resetImage(image) {
      if (dkrm) {
        image = scaleImage(image);
        dkrm.canvas.remove(dkrm.image);
        dkrm.canvas.add(image);
        dkrm.canvas.centerObject(image);
        image.setCoords();
        image.sendToBack();
      }
    }
    function loadImage(event) {
      var dataURI = event.target.result;
      if (dkrm) {
        fabric.Image.fromURL(dataURI, function(ximg) {resetImage(ximg);},
          {
            // options to make the image static
            selectable: false,
            evented: false,
            lockMovementX: true,
            lockMovementY: true,
            lockRotation: true,
            lockScalingX: true,
            lockScalingY: true,
            lockUniScaling: true,
            hasControls: false,
            hasBorders: false
          }
        );
      }
    }
    function readerError(event) {
      console.error("FileReader failed: Code " + event.target.error.code);
    }

    function doClick() {
      var el = document.getElementById("fileElem");
      if (el) {
        el.click();
      }
    }
    function handleImage(files) {
      var d = document.getElementById("img-container");
      if (files.length = 1) {
        var reader = new FileReader();
        reader.onload = loadImage;
        reader.onerror = readerError;
        reader.readAsDataURL(files[0]);
      }
    }
    function handleFiles(files) {
      var d = document.getElementById("fileList");
      if (!files.length) {
        d.innerHTML = "<p>No files selected!</p>";
      } else {
        d.innerHTML = "<p>Thanks</p>";
        var list = document.createElement("ul");
        d.appendChild(list);
        for (var i=0; i < files.length; i++) {
          var li = document.createElement("li");
          list.appendChild(li);
          
          var img = document.createElement("img");
          img.src = window.URL.createObjectURL(files[i]);;
          img.id = "design-image";
          img.onload = function() {
            window.URL.revokeObjectURL(this.src);
          }
          li.appendChild(img);
          
          var info = document.createElement("span");
          info.innerHTML = files[i].name + ": " + files[i].size + " bytes";
          li.appendChild(info);
        }
      }
    }
  </script>

**Comment by z3dev** [comment]
```javascript
  <script>
    var canvasSize = document.getElementById("img-canvas").clientHeight;
    var cropSize = canvasSize * 0.80;
    var dkrm = null;
    loadDarkroom();

    function loadDarkroom() {
console.log("reloading...");
      dkrm = new Darkroom('#design-image', {
        // canvas options
        minWidth: canvasSize,
        minHeight: canvasSize,
        //maxWidth: 500,
        //maxHeight: 500,
  
         plugins: {
           save: false,
           history: false,
           crop: {
             quickCropKey: 67, //key "c"
             minHeight: cropSize,
             minWidth: cropSize,
             ratio: 1
           }
         },
         init: function() {
           var cropPlugin = this.getPlugin('crop');
           var xoffset = (canvasSize - cropSize) / 2;
           cropPlugin.selectZone(xoffset, xoffset, cropSize, cropSize);
         }
       });
    }
    function scaleImage(image) {
      var width = image.getWidth();
      var height = image.getHeight();
      var scaleMin = 1;
      var scaleMax = 1;
      var scaleX = 1;
      var scaleY = 1;

      if (null !== dkrm.options.maxWidth && dkrm.options.maxWidth < width) {
        scaleX =  dkrm.options.maxWidth / width;
      }
      if (null !== dkrm.options.maxHeight && dkrm.options.maxHeight < height) {
        scaleY =  dkrm.options.maxHeight / height;
      }
      scaleMin = Math.min(scaleX, scaleY);
//console.log("scaleX: "+scaleX);
//console.log("scaleY: "+scaleY);
//console.log("scaleMin: "+scaleMin);

      scaleX = 1;
      scaleY = 1;
      if (null !== dkrm.options.minWidth && dkrm.options.minWidth > width) {
        scaleX =  dkrm.options.minWidth / width;
      }
      if (null !== dkrm.options.minHeight && dkrm.options.minHeight > height) {
        scaleY =  dkrm.options.minHeight / height;
      }
      scaleMax = Math.max(scaleX, scaleY);
//console.log("scaleX: "+scaleX);
//console.log("scaleY: "+scaleY);
//console.log("scaleMax: "+scaleMax);

      var scale = scaleMax * scaleMin; // one should be equals to 1

      image.setScaleX(scale);
      image.setScaleY(scale);

      return image;
    }
    function resetImage(image) {
      if (dkrm) {
        image = scaleImage(image);
        dkrm.canvas.remove(dkrm.image);
        dkrm.canvas.add(image);
        dkrm.canvas.centerObject(image);
        image.setCoords();
        image.sendToBack();
      }
    }
    function loadImage(event) {
      var dataURI = event.target.result;
      if (dkrm) {
        fabric.Image.fromURL(dataURI, function(ximg) {resetImage(ximg);},
          {
            // options to make the image static
            selectable: false,
            evented: false,
            lockMovementX: true,
            lockMovementY: true,
            lockRotation: true,
            lockScalingX: true,
            lockScalingY: true,
            lockUniScaling: true,
            hasControls: false,
            hasBorders: false
          }
        );
      }
    }
    function readerError(event) {
      console.error("FileReader failed: Code " + event.target.error.code);
    }

    function doClick() {
      var el = document.getElementById("fileElem");
      if (el) {
        el.click();
      }
    }
    function handleImage(files) {
      var d = document.getElementById("img-container");
      if (files.length = 1) {
        var reader = new FileReader();
        reader.onload = loadImage;
        reader.onerror = readerError;
        reader.readAsDataURL(files[0]);
      }
    }
    function handleFiles(files) {
      var d = document.getElementById("fileList");
      if (!files.length) {
        d.innerHTML = "<p>No files selected!</p>";
      } else {
        d.innerHTML = "<p>Thanks</p>";
        var list = document.createElement("ul");
        d.appendChild(list);
        for (var i=0; i < files.length; i++) {
          var li = document.createElement("li");
          list.appendChild(li);
          
          var img = document.createElement("img");
          img.src = window.URL.createObjectURL(files[i]);;
          img.id = "design-image";
          img.onload = function() {
            window.URL.revokeObjectURL(this.src);
          }
          li.appendChild(img);
          
          var info = document.createElement("span");
          info.innerHTML = files[i].name + ": " + files[i].size + " bytes";
          li.appendChild(info);
        }
      }
    }
  </script>
```

**Comment by MattKetmo** [comment]
Hello. Darkroom goal is only to transform an image into a (fabricjs) canvas. If you want user can load custom image (eg. using drag n drop or a button) and send the final image to your servers (eg. with an xhr), that's something you will have to code (or combine with other libraries).

**Comment by z3dev** [comment]
Agreed. I provided the example code in order to give you (Darkroom developers) some additional ideas.

I guess the ugliness comes from scaleImage() and resetImage() functions, where I had to go deep into Darkroom to get the values. Also the duplication of code... If you noticed.
