### ISSUE TITLE
Using darkroom.addEventListener right after instantiation

### ISSUE THREAD

**Issue by alanthai** [MattKetmo/darkroomjs#56]
I'm having a problem with adding event listeners to the element. At the start of my code, I'd like to add it like so:

    var darkroom = window.darkroom = new Darkroom('.my-element', {});
    darkroom.addEventListener('image:change', function() {});

The problem is that the image hasn't loaded yet. I don't see a way for me to do this properly. Currently I'm using a `setTimeout`, but it's too unreliable. Is there another way to do this?

Perhaps darkroom.canvas can be instantiated before the image is done loading?

**Comment by francislavoie** [comment]
My solution was to use a timeout loop. Probably a horrible solution, ideally the lib allows for a callback in the constructor.

    (function waitForInit() {
      if($(".darkroom-icon-crop").length > 0) {
        darkroom.addEventListener('image:change', function() {});
      } else {
        setTimeout(waitForInit, 50);
      }
    })();

Your condition for resetting the loop would probably need to change, but the idea is valid.

**Comment by MattKetmo** [comment]
There is an `initialize()` method to call things after darkroom is instancied:

```js
var darkroom = new Darkroom('.my-element', {
  initialize: function() {
    this.addEventListener('image:change', function() { /* ... */ });
  }
});
```

JavaScript is asynchronous ;)

**Comment by francislavoie** [comment]
Well, then. I didn't see that documented anywhere, that would've helped. Should be added to the README.md.

Thanks!

**Comment by MattKetmo** [comment]
You're right. I've completed example in readme: cd688c5
