### ISSUE TITLE
Restore img attributes after save

### ISSUE THREAD

**Issue by egorrishe** [MattKetmo/darkroomjs#59]
If before init `new Darkroom()` tag `<img>` has any html attributes (`id`, `alt`, etc.)
Then after Darkroom's "save button" tag `<img>` has only `src` attribute.

P.S.
Thanks for a great plugin!

**Comment by marcelgruber** [comment]
I'm assuming if you catch the save event you can add whatever you want back in using JQuery. I tried it a little bit but didn't work so instead I just took this out of the save event: `this.darkroom.selfDestroy();`. That way the editor will just stay there in its current size.

**Comment by MattKetmo** [comment]
For the next release I'm keeping the original image and only replacing the `src`. So all attributes will be kept. See #79.
