### ISSUE TITLE
Bower error on install

### ISSUE THREAD

**Issue by daniel-rosiak** [MattKetmo/darkroomjs#60]
Bower error on install

bower EMALFORMED    Failed to read /tmp/daniel/bower/darkroomjs-8784-TGlera/bower.json

Additional error details:
Unexpected token }

Seems like something is wrong in bower file. Maybe the last comma in bower.json?

**Comment by MattKetmo** [comment]
Erf, thanks. Fix in a2e1347.

**Comment by daniel-rosiak** [comment]
Thx, but will you consider pushing the changes into some new tag ex v2.0.1? Bower is refreshing package changes faster if they are provided in new tag.
