### ISSUE TITLE
How to access the Save Event - or send the new image to a form

### ISSUE THREAD

**Issue by peterbournecommunications** [MattKetmo/darkroomjs#61]
Hi,

Sorry - I'm sure its a dumb question - but Google searches on this excellent cropper tool produce very few results...

How do I actually hook into the Save Event?

(I just need to trigger some javascript to save my new nicely cropped image)... and can't seem to figure it.

Many thanks,

Peter

**Comment by MattKetmo** [comment]
Just pass a callback to the save plugin:

```js
new Darkroom('#target', {
    save: {
      callback: function() {
        // do what you want
      }
    }
  }
});
```

Default callback is https://github.com/MattKetmo/darkroomjs/blob/master/lib/js/plugins/darkroom.save.js#L7

**Comment by peterbournecommunications** [comment]
Great - thanks - that's easier than I was trying!!

**Comment by peterbournecommunications** [comment]
Sorry - just want to check something. I still don't seem to be able to get the saved image to send to my server PHP script. Or rather I do - but the size of the object is quite large - and my PHP script dies from exhausted memory. I use the same script when sending other images - and it works fine. Here's the code of the darkroom save option:

save: {
				callback: function() {
					console.log('saved!');
					var oMyForm = new FormData();
					oMyForm.append("ContentID", $('#ID').val());
					oMyForm.append("Title", $('#Title').val());
					oMyForm.append("ContentType", 'content');
					//Now the file (large version)
					var oBlob = dkrm.sourceImage.toDataURL();
					oMyForm.append("ImgFile", oBlob);
					
					oReq = new XMLHttpRequest();
					oReq.open("POST", "image_header_upload.php");
					oReq.onreadystatechange = ClientSideUpdate;
					oReq.send(oMyForm);
					return true;
				}

My intention is to be able to drop a large (straight from digital camera) image onto the canvas, crop an area of 1400x480 pixels and then save it (which uploads and stores the file on the server).

But even when trying to select a small crop area (140x48 etc) - I get memory exhausted on the server - and the file does seem too large for such a file. My complete darkroom initialisation is:

var dkrm = new Darkroom('#target', {
			// Size options
			minWidth: 140,
			minHeight: 48,
			maxWidth: 1400,
			
			// Plugins options
			plugins: {
			crop: {
			  ratio: 1400/480,
			  maxWidth: 1400,
			  maxHeight: 480
			},
			save: {
				callback: function() {
					console.log('saved!');
					var oMyForm = new FormData();
					oMyForm.append("ContentID", $('#ID').val());
					oMyForm.append("Title", $('#Title').val());
					oMyForm.append("ContentType", 'content');
					//Now the file (large version)
					var oBlob = dkrm.sourceImage.toDataURL();
					
					oMyForm.append("ImgFile", oBlob);
					
					oReq = new XMLHttpRequest();
					oReq.open("POST", "image_header_upload.php");
					oReq.onreadystatechange = ClientSideUpdate;
					oReq.send(oMyForm);
					return true;
				}
			}
		},
		
		// Post initialize script
		initialize: function() {
			$('.current-image').fadeTo( "fast" , 1);
			$('#instruction').css('opacity','0'); 
			
			var cropPlugin = this.plugins['crop'];
			cropPlugin.requireFocus();
			
			}
		});


Many thanks if you can shed any light Matt.

**Comment by peterbournecommunications** [comment]
I guess the point of my question is:

Does    dkrm.sourceImage.toDataURL()    just send the new resized data (not the original full image)?

Thanks

**Comment by peterbournecommunications** [comment]
Hi - I'm still really struggling to extract the resized item to send to the server - that's all I need to do! I don't want to send the original filesize up to the server (even if its been cropped to the proportion I need). I want to resize it in the browser (via a Canvas) and then send that blob up to the server.

Not sure why I'm finding this so difficult!

For example a large 5000x4000px file (for example) - I want to crop to 1400x480px - and just send the 1400px x 480px of data up to store etc.

Many thanks,

Peter

**Comment by marcelgruber** [comment]
I'm having the same exact issue!

**Comment by marcelgruber** [comment]
I figured it out! All the more reason we should start beefing up the documentation because this is definitely a crucial component of this excellent tool. 

When you change the image, the actual URL of the image never changes. Just look at the darkroom html. It stays the same. What does change is the canvas. So if you want to actually generate the Base64 data for the new edited image, you need to ASK the canvas for it.

So in your save plugin details you do this.

                       save: {
                                    callback: function() {
                                       // get rid of the toolbar and finalize
                                        this.darkroom.selfDestroy();
                                       
                                        var newImage = dkrm.canvas.toDataURL();
                                        
                                        // Set your data that will be sent to reflect this change
                                        self.fileData().modifiedDataURL = dkrm.canvas.toDataURL();
                                    }
                                }

**Comment by peterbournecommunications** [comment]
Thanks! Unfortunately I had to bail on this and find another solution using a different tool. Similar - but allowed a bit more flexibility in what I needed to do - that I just couldn't figure out in Darkroom.
