### ISSUE TITLE
support for react and jsx 

### ISSUE THREAD

**Issue by stepancar** [MattKetmo/darkroomjs#62]
Hello @MattKetmo !
Thank you for this project!
Do you have any plans for integration your library with react jsx?
I Added d.ts for using your libs with typescript https://github.com/borisyankov/DefinitelyTyped/pull/5784.
may be you want add any comments/ tests? 
Thank you!

**Comment by stepancar** [comment]
And what about integration with npm? May be you push you project to npm?

**Comment by MattKetmo** [comment]
Hello,
Package is avaiable via npm.
I've no plan to support react/jsx (I don't use it).
About d.ts I didn't know about that project. Thanks for the PR.

**Comment by stepancar** [comment]
i can download this packige via npm, but i can't import this lib like node module.

**Comment by chentsulin** [comment]
This lib don't have commonjs module for npm, but this will block most of browserify and webpack user.

**Comment by MattKetmo** [comment]
Feel free to submit a PR ;-)

**Comment by chentsulin** [comment]
@MattKetmo #67 should solved this.

**Comment by taltk9** [comment]
I'm working to apply Darkroom as a React component, cause I need a picture editor at my app.
So, how should I share this implementation?

**Comment by MattKetmo** [comment]
This will be fixed in next major version #79
