### ISSUE TITLE
Place crop area on image on init

### ISSUE THREAD

**Issue by ZaneCEO** [MattKetmo/darkroomjs#73]
Hi, I'm switching from jCrop to Darkroom.js. I need to set the cropping area on init so that the user finds the cropping grid already placed on the image on load. In jCrop i used `setSelect : [0, 0, x, y]`. What is the Darkroom.js equivalent?

Thanks!

**Comment by MattKetmo** [comment]
Hello. You can do this: https://github.com/MattKetmo/darkroomjs/blob/e7d119fb370fd30be9d64c57348f3aabdf6c01b4/demo/index.html#L161
