### ISSUE TITLE
Darkroom is not defined

### ISSUE THREAD

**Issue by rochapablo** [MattKetmo/darkroomjs#76]
I'm using Gulp and each execution i got the message:

```
app\src\product\edit.js: line 267, col 23, 'Darkroom' is not defined.
```

Anyway the plugin it's working and at the browser there's no error like that.

**Comment by MattKetmo** [comment]
Hello. I have no idea what you're talking about. `app\src\product\edit.js` is not a file of my library.
Next major release is build with webpack instead of gulp (which is compliant with standard loaders) so I guess it may resolve your problem.
