### ISSUE TITLE
saving?

### ISSUE THREAD

**Issue by zstew** [MattKetmo/darkroomjs#8]
How does one get the final product of editing in say in a URI or base64 image?

I was guessing that the 'save' parameter took a function and the final image would be passed to that function.  Seams like save just turns off editing?

I can hack my own save function to snapshot the final product, but I'm guessing there's a better way.

**Comment by z3dev** [comment]
actually, fabric.js supports options on the toDataUrl() function via an object. Why not do the same for snapshotImage()?

**Comment by digz6666** [comment]
@MattKetmo snapshotImage() method is renamed or removed?

**Comment by MattKetmo** [comment]
That method was just a proxy to the fabric toDataUrl.
You can directly call that method:
 
```js
var base64Data = darkroomInstance.sourceImage.toDataURL(fabricOptions);
```

**Comment by digz6666** [comment]
@MattKetmo Thank you.

I have another question is that how to scale the image after crop?
For example if we render image with 1920x1080 pixels on 800x600 pixels canvas, image is resized on the canvas. After cropping how to get correctly scaled image?

```javascript
var base64Data = darkroomInstance.sourceImage.toDataURL( {
    left: cropPlugin.cropZone.left,
    top: cropPlugin.cropZone.top,
    width: cropPlugin.cropZone.width,
    height: cropPlugin.cropZone.height
});
```

**Comment by nicosomb** [comment]
Hello @MattKetmo!

I want to get sourceImage.toDataURL in callback save. 
What is the good way to retrieve it?

**Comment by 0000sir** [comment]
@digz6666 did your code is about saving a larger image than the maxHeight & maxWidth option? where should I place it at?

**Comment by marcelgruber** [comment]
@nicosomb  I believe that has been addressed in the FAQ :)
